### PR TITLE
Bulk from raklib removed and more.

### PR DESCRIPTION
**Pull request by RazvanDu**
Removed a ton of bulk from the raklib which should improve performance but it does still require some tweaking!

### CODE REVIEW

**Comment by RazvanDu** [comment]
Keep in mind, the stuff I've removed were not entirely useless but I don't think they're worth keeping.

**Comment by RazvanDu** [comment]
Actually I think this would be helpful, it's up to you if you wanna merge it or not but take a good look at it.

**Comment by ethsmith** [comment]
Either way thanks for contributing

**Comment by RazvanDu** [comment]
After rigorous testing the PR causes more issues than it fixes, although removing the streams in the raklib wouldn't be a bad idea, it would require more work, I'm not sure if I recommend committing  this PR.

**Comment by DefinitlyEvil** [comment]
In my opinion, I want to keep RakNet a individual module instead of mixing it together with Dragonet. So some of this PR is good so I will manually merge them. ;)

**Comment by RazvanDu** [comment]
Alright that's cool

**Comment by DefinitlyEvil** [comment]
Dude do not remove parts or it will difficult to update source by the original RakLib source.

**Pull request closed without merging**
