### PR TITLE
All build issues (#42 and #45) fixed

### PR DESCRIPTION
**Pull request by ashquarky**
So, you guys probably remember the issues people are having with building the latest Dragonet on their PCs. I said I had an idea, and here it is!

Basically, I've moved all Dragonet's code into the "Dragonet-core" folder, made a parent project that compiles both Dragonet and Glowkit, tweaked Circle into being nice and actually got a successful build! Check it out [here](https://circleci.com/gh/QuarkTheAwesome/Dragonet/14).

The only issue I found is that the new repo you guys set (therealms.us) doesn't contain the sqlite stuff that most plugins need. Other than that, it seems to work flawlessly!

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
Nice work! :D

**Comment by ashquarky** [comment]
The build [failed](https://circleci.com/gh/DragonetMC/Dragonet/35) for you... Hmm. Looks like it's not actually using the Glowkit that's built, instead using the one from the Glowstone repo.

Since you removed the Glowstone repo, it's not getting the Bukkit it needs and the build is failing. A temporary fix is to add the Glowstone repo back in while I tweak stuff into working. Sorry about that - looks like my Circle box had Bukkit cached.

**Comment by DefinitlyEvil** [comment]
xD

**Comment by ashquarky** [comment]
Okay! I've fixed Maven (Dragonet-core was depending on 1.8.6 while we were building 1.8.7 - oops) but I'm still getting errors - looks like Glowstone++ is outdated, specifically GlowScoreboard and GlowTeam.

See it for yourself - here's [our GlowScoreboard](https://github.com/DragonetMC/Dragonet/blob/master/Dragonet-core/src/main/java/net/glowstone/scoreboard/GlowScoreboard.java) and here's [the one from Glowstone++](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/scoreboard/GlowScoreboard.java).

Anyway, you can get everything working by going into Dragonet-core/pom.xml and changing properties/bukkit.version to 1.8.**7**-R0.1-SNAPSHOT.

**Comment by DefinitlyEvil** [comment]
Nvm dude, @mastercoms fixed it for us! ;)

**Comment by mastercoms** [comment]
> The only issue I found is that the new repo you guys set (therealms.us) doesn't contain the sqlite stuff that most plugins need. Other than that, it seems to work flawlessly!

This is a change in Glowstone++, because repo.glowstone.net was down. I accidentally made the URL http://repo.therealms.us/content/groups/public/ instead of https://repo.therealms.us/repo/content/groups/public/. This is fixed upstream now. I would recommend merging to fix this.

**Pull request merged**
