### PR TITLE
Fixed your circle ci builds.

### PR DESCRIPTION
**Pull request by mastercoms**
This will fix your circle CI builds. The ones that were failing. They will pass now. You'll get a green passed badge on your readme too.

I unfortunately had to remove Sponge stuff from the build process, but that's in [a new plugin](https://github.com/GlowstonePlusPlus/Bukkit2Sponge) anyway.

Sorry about all the commits, it took me a while to realize how your project was setup. Also I did this without an IDE.

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
Thanks so so much, bro! You helped a lot! :D

**Comment by mastercoms** [comment]
Glad to help!

**Comment by DefinitlyEvil** [comment]
@mastercoms And could you please help us a little bit on the MCPE crafting? The MCPE crafting packets are really weird, it only sends the change on the inventory so we have to check it is a crafting action or a inventory transcation action. 
Here's what I tried to do but I don't think it is a good way: 
http://github.com/DragonetMC/Dragonet/blob/master/Dragonet-core/src/main/java/org/dragonet/net/translator/topc/WindowSetSlotPacketTranslator.java

**Comment by mastercoms** [comment]
I am not that familiar with the MCPE protocol. I'll try to help, though. Also, you should definitely merge this: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/7c6b61db1e43f0433146605b6b3ca58b4986c5bd

**Comment by DefinitlyEvil** [comment]
@mastercoms Nice to hear that! :D

**Comment by mastercoms** [comment]
I'm done.

**Comment by DefinitlyEvil** [comment]
Cool!

**Comment by mastercoms** [comment]
I won't be able to help until I fix the Glowstone++ crafting bugs. I've almost fixed everything, there are just a few rare errors that come up.

**Comment by DefinitlyEvil** [comment]
@mastercoms Okay. ;)

**Comment by ashquarky** [comment]
Can I just quickly ask how you got it to run `(cd Dragonet-core && mvn package)`? It's not in circle.yml, and it's not running on my fork. It just kinda stops after compiling Glowkit.

**Comment by mastercoms** [comment]
It is in the circle-ci settings, dependency command.

**Comment by ashquarky** [comment]
Huh, alright. Thanks!

**Comment by mastercoms** [comment]
Any time.

**Comment by Creeperface01** [comment]
Why can't you look at pocketmine crafting?

**Comment by wordandahalf** [comment]
@Creeperface01  PHP =/= Java

**Comment by mastercoms** [comment]
But you can certainly look at the meaning of their PHP code.

**Pull request merged**
