### PR TITLE
fix block placing

### PR DESCRIPTION
**Pull request by julianwi**
Fixes the block placing lag. Also door opening works mostly with this change.

### CODE REVIEW

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Said that it was to do with some packets being wrong because he has to debug them or something.

**Comment by mastercoms** [comment]
Are you not going to test this change?

**Comment by RandomAltThing** [comment]
@mastercoms I can't

**Comment by ethsmith** [comment]
@RandomAltThing why not?

**Comment by RandomAltThing** [comment]
@TekkitCommando Because i can't. End of.

**Comment by ethsmith** [comment]
@RandomAltThing ok..

**Comment by DefinitlyEvil** [comment]
@julianwi We must check the data before we process it to prevent hacking, I will look into it later. ;) Thanks for contributing.

**Comment by julianwi** [comment]
why did you close my pull request?

**Comment by RandomAltThing** [comment]
@julianwi Read the label. "PR: Cannot Merge". It is either fixed in a commit, or has errors, or is not needed. Please don't argue with the developers in this organisation (such as me)

**Comment by DefinitlyEvil** [comment]
I will manually add this. ;)

**Comment by mastercoms** [comment]
@RandomAltThing I don't think he was arguing, all he did was ask a question.

**Comment by DefinitlyEvil** [comment]
@mastercoms Agree.

**Comment by ethsmith** [comment]
@RandomAltThing woke up on the wrong side of the bed it seems

**Comment by DefinitlyEvil** [comment]
@TekkitCommando What was that means?

**Comment by ethsmith** [comment]
@DefinitlyEvil it's a joke means he's in a bad mood

**Pull request closed without merging**
